version: '3'

services:

  database:
    image: mysql:8.0.35
    container_name: database_compta
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: compta
      image: mysql:8.0.35
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - dev
      

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_compta
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - dev

  www:
    build: docker
    container_name: www_compta
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

  mail:
    image: maildev/maildev
    container_name: Maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
    networks:
      - dev 
      
networks:
  dev:

volumes:
  database_data:
