# config/routes.yaml

app_login:
    path: '/login'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction'


app_home:
    path: '/'
    controller: 'App\Controller\HomeController::home'
    
app_contact:
    path: '/contact'
    controller: 'App\Controller\ContactController::contact'
  

upload_pdf:
    path: /upload-pdf
    controller: App\Controller\PdfController::uploadPdf
